django/monSite/monSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

django/monSite/polls/urls.py
from django.urls import path 
from . import views 

#définition d'un espace de nom "app_name" pour les urls de notre application polls
#de façon à pouvoir cibler les paths sans ambiguité 
app_name = "polls"
urlpatterns = [
    #/polls/
    path('', views.index, name="index"),
    #/polls/2/
    path('<int:question_id>', views.detail, name="detail"),
    #/polls/2/results/
    path('<int:question_id>/results/', views.results, name="results"),
    #/polls/2/vote/
    path('<int:question_id>/vote/', views.vote, name="vote"),
    
]

django/monSite/polls/models.py
import datetime #datetime est un composant de python interne, on a pas besoin de préciser le module
from django.db import models
from django.utils import timezone

#définir un model revient à définir une classe
#on utilise les fonctionalités de models pour définir les champs
#de notre entité
class Question(models.Model):
    question_text = models.CharField(max_length=200) #un charfield est l'équivalent d'un varchar
    date_published = models.DateTimeField()

    # __str__ est l'équivalent de toString() il permet au langage
    # d'avoir un moyen de décrire une entité par du texte 
    # __str__ est une méthode utilisable dans tous les objets car appartenant a la classe "mère"
    # de tous les objets en Python : "Object"
    def __str__(self):
        return self.question_text
    
    #exemple d'une méthode de classe personnalisée 
    def was_published_recently(self):
        # vérifie que la question ait été publiée dans un intervalle d'un jour
        return self.date_published >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    #pour définir une relation on définit une foreignKey
    #le premier paramètre est la classe avec laquelle établir une relation
    #le second paramètre on_delete détermine l'action suivant la suppression
    #de l'entité référencée par la clé étrangère. 
    # Cascade signifie que le choix est suppirmé également
    question = models.ForeignKey(Question, models.CASCADE) 
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    
    

django/monSite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice
# Create your views here.

def index(request):
    #récupère les 3 dernières questions triées par date 
    latest_questions = Question.objects.order_by('-date_published')[:3]
    return render(request, 'polls/index.html', { 'question_list' : latest_questions })

def detail(request, question_id):
    #récupère la question dont l'id correspond au paramètre
    #get_object_or_404 est un raccourci permettant d'envoyer une erreur 404 si jamais l'objet
    #n'a pas été trouvé en base
    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/detail.html', {'question' : question})

def results(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    try:
        choice = question.choice_set.get(id=request.POST['choice'])
    #le mot clé except permet de traiter une exception
    #l'exception est de type KeyError (erreur de clé)
    #et le message d'exception sera celui de Choice.DoesNotExist explicitant qu'une entité Choice
    #n'existe pas
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Erreur survenue, veuillez réessayer"
        })
    #else définit le comportement à suivre si tout se passe bien 
    #autrement dit: incrémenter le nombre de votes du choix selectionné 
    else:
        choice.votes += 1
        choice.save()
        return HttpResponseRedirect(redirect_to=reverse('polls:results', args=[question.id]))
        

django/monSite/polls/templates/polls/detail.html
<h1>
    {{ question.question_text }}
</h1>
{% if error_message %}
    <h3>{{error_message}}</h3>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input id="choice{{ forloop.counter }}" type="radio" name="choice" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
        </label>            
    {% endfor %}
    <input type="submit" value="Vote">
</form>

django/monSite/polls/templates/polls/index.html
{% if question_list %}
<ul>
    {% for question in question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{question.id}} - {{question.question_text}}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
    <p>No questions available</p>
{% endif %}

django/monSite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> 
            {{ choice.choice_text }}
            --
            {{ choice.votes }} 
            vote{{choice.votes|pluralize}}
        </li>
    {% endfor %}
</ul>